### ISSUE TITLE
Array with initializer but no length errors in SV-COMP SoftwareSystems

### ISSUE THREAD

**Issue by sim642** [goblint/cil#19] opened 2020-10-20 13:34 UTC
In my own run of Goblint on SV-COMP SoftwareSystems category, Goblint crashed with `Errormsg.Error` exception

```
Unimplemented: foldLeftCompound: TArray with initializer and no length
```

https://github.com/goblint/cil/blob/60f8db1c3771f1f36849fdbcaef5d48a5aee0679/src/cil.ml#L6444

on the following benchmarks:

- [x] ldv-linux-3.4-simple/32_1_cilled_ok_nondet_linux-3.4-32_1-drivers--media--rc--keymaps--rc-lirc.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.i (line 104)
- [x] ldv-linux-3.4-simple/32_1_cilled_ok_nondet_linux-3.4-32_1-drivers--media--video--gspca--gspca_benq.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.i (line 3583)
- [x] ldv-linux-3.4-simple/32_1_cilled_ok_nondet_linux-3.4-32_1-drivers--media--video--gspca--gspca_stv0680.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.i (line 3577)
- [x] ldv-linux-3.12-rc1/linux-3.12-rc1.tar.xz-144_2a-drivers--usb--wusbcore--wusb-cbaf.ko-entry_point.cil.out.i (line 3765)

---

For example, the first one does
```c
static struct rc_map_table lirc[] = { };
```
which should be simply defining an array of length 0, no?

**Comment by sim642** [comment] 2020-10-20 17:06
A year ago I hit this somewhere as well (possibly the same benchmarks) and just hackily removed the error being raised: https://github.com/sim642/cil/commit/c6433c0e50b4e643fecb7fabe613c18a5038acab. But this change hasn't gone anywhere because I doubt it's so easy, otherwise CIL would've been that way to begin with.

**Comment by michael-schwarz** [comment] 2020-10-22 12:14
This is not a CIL bug,

**Comment by sim642** [comment] 2020-10-22 12:20
Doesn't `unimp` (which prints `Unimplemented`) mean something that is possible and should be there but the CIL people just never got around to implementing it? As opposed to similar `bug` or `error`.

**Comment by michael-schwarz** [comment] 2020-10-22 12:26
Yes, but it is an issue that only happens because we call this thing outside of the scope it was intended for in Goblint.
CIL has no problem with these input files. The problem seems to be that the size is somehow not set inside of `TArray` if the initializer is empty. It works for non-empty initializers.

We can't really construct a zero initializer for something that we don't know the length of, so I think it makes sense that this exception is thrown here.

This is where we call it in Goblint:
https://github.com/goblint/analyzer/blob/212c9cd571f2bb88005154785c0ca42ea45186f5/src/framework/myCFG.ml#L397

**Comment by michael-schwarz** [comment] 2020-10-22 13:30
Ok, the best place to fix it ended up being CIL after all :)

**Comment by michael-schwarz** [comment] 2020-10-22 13:57
The last example apparently is not fixed by this yet.

**Comment by michael-schwarz** [comment] 2020-10-23 06:03
The last example is a bit more complicated, it involves a `flexible array member` which is a C99 feature where the last member of a structure may be an array of incomplete type.

The standard gives this example usage

~~~C
struct s { int n; double d[]; };
struct s *p = malloc(sizeof (struct s) + sizeof (double [m]));
// This now behaves as if we had declared struct { int n; double d[m]; } *p;
~~~

For the other cases, we solved the problem by patching the array to be the correct type:
~~~C
int a[] = {5,6,7};
// a should have type int[3]
~~~
This is also not a problem when there are typedefs, because `typedef int[] example;` is not valid C.

~~~C
typedef int[] example;
example e1 = {};
example e2 = {2, 3};
~~~ 
Is therefore not a thing that can happen.

**But in this case, we can't patch the type as seen by this example**
~~~C
struct blub {
  int member;
  int m2[];
};

struct blub one = {0,{}};
struct blub two = {0,{0,0}};
~~~

It would not be ok to set the type of `m2` to either `int[0]` or `int[2]`, it should stay `int[]`.

**Comment by michael-schwarz** [comment] 2020-10-23 07:46
Fixed via https://github.com/goblint/analyzer/commit/c7b25d229a7a59c4b61f159e8eae3c484f14ffbc

**Closed by michael-schwarz** 2020-10-23 07:46 UTC
